# Implementing Word Embedding Using Keras and Tensorflow

In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
## Sentence

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [21]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good developer',
 'understand the meaning of words',
 'your videos are good']

In [22]:
voc_size = 10000 ## defining the vocabulary size

In [23]:
## One hot representation

one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[4855, 6372, 5670, 2137],
 [4855, 6372, 5670, 6101],
 [4855, 1002, 5670, 9986],
 [8911, 7401, 8165, 8454, 1156],
 [8911, 7401, 8454, 937],
 [4416, 4855, 4756, 5670, 1197],
 [4887, 3933, 5428, 8454]]

In [34]:
## word Embedding Representation

from tensorflow.keras.layers import Dense, Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [25]:
import numpy as np

In [26]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_repr, padding='post', maxlen=sent_length)
print(embedded_doc)

[[4855 6372 5670 2137    0    0    0    0]
 [4855 6372 5670 6101    0    0    0    0]
 [4855 1002 5670 9986    0    0    0    0]
 [8911 7401 8165 8454 1156    0    0    0]
 [8911 7401 8454  937    0    0    0    0]
 [4416 4855 4756 5670 1197    0    0    0]
 [4887 3933 5428 8454    0    0    0    0]]


In [27]:
dim = 10 # setting the dimension


In [ ]:
model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [38]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
emb = model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step


In [40]:
embedded_doc[0]

array([4855, 6372, 5670, 2137,    0,    0,    0,    0])

In [46]:
emb

array([[[-0.00644574,  0.03200277, -0.01588947, -0.04655401,
          0.02896993, -0.04612955, -0.01705099, -0.04461005,
          0.0339223 ,  0.00557093],
        [-0.00500967,  0.0497859 ,  0.01441694,  0.01726711,
          0.04721699, -0.01275206, -0.0108655 , -0.00914776,
          0.01484518, -0.03355126],
        [ 0.02969862, -0.03537319,  0.03751704, -0.00023421,
          0.01690358,  0.01748116,  0.00601222,  0.01971597,
         -0.03499477,  0.03729871],
        [ 0.00970147,  0.02874819,  0.0056586 , -0.04447804,
         -0.03731301,  0.00642707, -0.0164956 ,  0.01717622,
          0.0123929 , -0.04147254],
        [-0.02404779,  0.00885642, -0.0453982 , -0.01267383,
          0.04541362, -0.02586244, -0.04166566, -0.01848394,
         -0.0158966 ,  0.00385281],
        [-0.02404779,  0.00885642, -0.0453982 , -0.01267383,
          0.04541362, -0.02586244, -0.04166566, -0.01848394,
         -0.0158966 ,  0.00385281],
        [-0.02404779,  0.00885642, -0.0453982 , -0.0

## Vector representation of the 1st sentence after applying the Word2vec model

In [ ]:
emb[0, 0] # or emb[0][0]

array([-0.00644574,  0.03200277, -0.01588947, -0.04655401,  0.02896993,
       -0.04612955, -0.01705099, -0.04461005,  0.0339223 ,  0.00557093],
      dtype=float32)